- README.md
- db.js
- indexes/social.js
- operators.js
- seekers.js
- test/base-index.js
- test/operators.js
- test/social-index.js
- test/validate.js
To be merged simultaneously with https://github.com/ssb-ngi-pointer/jitdb/pull/27
> move operators from jitdb to ssb-db2

- README.md
- db.js
- operators/index.js
- operators/social.js
- package.json
- test/social-index.js
Example usage of PR https://github.com/ssb-ngi-pointer/jitdb/pull/28, in draft mode because it's incomplete and requires a release of jitdb after that PR is merged.
> operators for social indexes

- db.js
- indexes/partial.js
- indexes/plugin.js
- log.js
> use ~/.ssb/db2 folder

- .prettierrc
- compat/ebt.js
- compat/history-stream.js
- compat/index.js
- db.js
- indexes/base.js
- indexes/partial.js
- indexes/plugin.js
- indexes/social.js
- log.js
- msg-utils.js
- operators/index.js
- operators/social.js
- package.json
- seekers.js
- test/base-index.js
- test/createHistoryStream.js
- test/operators.js
- test/social-index.js
- test/validate.js
Like https://github.com/ssb-ngi-pointer/jitdb/pull/32
> Format code automatically with Prettier

- db.js
- index.js
- indexes/base.js
- indexes/social.js
- package.json
- test/base-index.js
> add close() in db.js

- README.md
- migrate.js
- package.json
- test/migration.js
> allow using pull-drain-gently in migrate

- indexes/social.js
> change import from level-codec to flumecodec

- migrate.js
I needed this in order to call `start()` in Manyverse, new version would be appreciated
> add manifest for migrate plugin

- db.js
- operators/social.js
> Fix register index for queries

- operators/index.js
For issue #52 
Hardest part of this PR was setting up git config author and ssh keys on my phone
> refactor operators to use jitdb operators

- indexes/private.js
What this PR does: see the inline comments
> improve private index save/load methods

- db.js
- indexes/base.js
- indexes/mentions.js
- indexes/plugin.js
After the log-sharing PR, this argument is no longer needed
> remove unused log arg to plugins

- db.js
- indexes/base.js
- test/basic.js
> Fix concurrency bug in base index save

- db.js
> wait for getAllLatest before publish or add

- migrate.js
Manyverse uses ssb-db@19.3.1 and the `sizeStream` in migrate wasn't working, while ssb-db2 uses ssb-db@20.3.0 for the tests.
I changed ssb-db to 19.3.1 in this module's package.json, then tests didn't pass either. Then I fixed the implementation until tests passed for 19.3.1. And then I changed package.json back to 20.3.0. Unfortunately I don't know a way of installing both versions and running tests, so we just have to remember to manually test 19.3.1 if we change `migrate`'s implementation. But now we know `migrate` works for both versions.
> fix migrate for ssb-db@19.3.1

- compat/history-stream.js
- db.js
- index.js
- migrate.js
- package.json
- test/base-index.js
- test/migration.js
This should be the last PR I need merged before Manyverse can get ssb-db2, I think.
> Add manifest

- operators/index.js
- seekers.js
- test/operators.js
This one is just because I want to replace another simple API inside Manyverse and seemed easy to do.
> add contact(feedid) operator

- compat/history-stream.js
- db.js
- indexes/base.js
- indexes/ebt.js
- indexes/full-mentions.js
- log.js
- package.json
- test/basic.js
- test/delete.js
Fixes #60 by making delete and deleteFeed work again. This depends on https://github.com/ssb-ngi-pointer/jitdb/pull/74 and https://github.com/flumedb/async-flumelog/pull/13.
> Fix delete

- indexes/base.js
- indexes/ebt.js
- indexes/full-mentions.js
Just some minor things I noticed
> Minor tweaks to index building

- db.js
I'm moving this partial stuff elsewhere so can be removed from db.js
> Remove partial stuff

- db.js
- indexes/base.js
- indexes/ebt.js
- indexes/plugin.js
- indexes/private.js
- log.js
- seekers.js
Just some shuffling around of code, and some renames. I was studying the code, trying to understand how `private` affects performance (I have some ideas I'd like to discuss with you later, because it seems `private.decrypt` during log stream has a noticeable impact on initial sync), but while studying code I noticed these possible refactors. Feel free to ask me to rollback some if they've gone too far.
> refactor bipf pointers and other minor refactors

- db.js
- indexes/private.js
These two minor changes are needed to run in the browser. This fixes #87.
> Minor browser fixes

- operators/index.js
- seekers.js
- test/operators.js
> Add isPublic operator

- db.js
- migrate.js
- test/query-waits-migrate.js
> make query() wait for migrate to sync logs

- .github/workflows/node.js.yml
- benchmark/index.js
- package.json
Some of this was copied from jitdb. I'm interested in adding this now, before I attempt one trick to speed up initial indexing.
> add benchmark scripts (in CI as well)

- indexes/plugin.js
I'm trying to fix #112. I noticed that before we were writing the offset and afterwards we write the changes for an index. So if you are unlucky you might hit the spot between the put and the batch write and get an inconsistent state of the index.
> Make sure offset is written after the batch for indexes

- test/ebt.js
> Fix ebt tests by waiting for the correct index

- indexes/base.js
- log.js
> private is a reversed keyword in js

- indexes/plugin.js
Was running benchmark locally and noticed that initial indexing was erroring for me. This handles the problem.
> Fix write error when closing

- README.md
- db.js
- test/basic.js
This should fix #119. Please note it also changes get to err if the key is not found. This is the same behaviour as ssb-db.
> Add getMsg

- db.js
- package.json
- test/operators.js
> Support or() alone at the start of a query()

- operators/index.js
- package.json
> Change author() operator to prefix

- migrate.js
- package.json
- test/migration.js
1st commit is failing test, 2nd commit fix
> Fix migrate to not read old log pre-decrypted

- db.js
- test/operators.js
> Expose operators

- package.json
- test/operators.js
> support db.query(live(), toPS())

- operators/index.js
- package.json
> Use prefix offset & map for key

- benchmark/index.js
- db.js
- package.json
- status.js
- test/base-index.js
- test/basic.js
> update db.getStatus() to be obv and include jitdb status

- benchmark/index.js
- package.json
@arj03  What do you think? Is this bench useful? Not necessary to merge.
> add benchmark for two indexes updating concurrently

- full-mentions.js
- test/operators.js
I'll need this for ssb-blobs-purge
> expose extra operator fullMentions

- compat/ebt.js
> EBT compat plugin avoids overriding sbot.post

- indexes/full-mentions.js
Just a cosmetic thing. 
I stumbled upon this while I was thinking about making another level index for abouts such as `{type:'put', key: [content.about, "name"], value: processed}` (might make a PR for that this week, I think it'll be much more efficient than looking for **all** about msgs, what ssb-social-index does)
> refactor: avoid pyramid of ifs and ~ operator

- README.md
- compat/db.js
- compat/log-stream.js
- package.json
- test/compat.js
- test/createLogStream.js
- sbot.createLogStream
- sbot.whoami
> More db1 compat

- compat/db.js
- test/compat.js
> add sbot.ready() to compat/db

- benchmark/index.js
This should be merged before https://github.com/ssb-ngi-pointer/ssb-db2/pull/168, and then we can rebase that one and see the new benchmark results
> benchmark indexing with maxCpu=86

- log.js
See https://github.com/ssb-ngi-pointer/jitdb/issues/118#issuecomment-777096352
This was a clear win, I think.
> tweak too-hot params

- README.md
- about-self.js
- indexes/about-self.js
- test/about-self.js
- test/query-waits-migrate.js
Adds an index for self-assigned about messages.
> Add self-assigned about index

- indexes/full-mentions.js
- test/full-mentions.js
> add test for full-mentions in live mode

- db.js
- test/basic.js
> add test for base status always in getStatus()

- db.js
- indexes/base.js
So that it uses `registerIndex()`, and then we can be more confident about putting more logic in `registerIndex()` and knowing it will apply to base too.
> refactor base index to use registerIndex()

- benchmark/index.js
- db.js
- indexes/keys.js
- operators/index.js
- package.json
So far this just adds a new benchmark. Will add implementation code later.
> rework keys index

- README.md
- log.js
> allow all too-hot params to be configured

- migrate.js
Found this trying to test this feature.
> Fix missing config in migrate

- package.json
Doing this as a PR just to see if tests pass, and benchmark.
> update async-append-only-log and jitdb

- migrate.js
- test/migration-alone.js
- test/migration.js
This has good performance on mobile
> emit progress events every 3s

- migrate.js
Two ideas:
- In non-live mode, when the setInterval triggers, only call the `sbot.emit` if the number is different (I detected in production that sometimes the number is the same, I guess it was busy with indexing or something)
- In live mode, don't emit every 100th time, instead, use an interval timer too
> optimize how migrate progress events are done

- db.js
- test/about-self.js
- test/compat.js
- test/createLogStream.js
- test/ebt.js
- test/full-mentions.js
- test/operators.js
> fix db.close() to close the log as the last step

- indexes/plugin.js
I ran ESLint on this repo and spotted a small bug. Here's the fix.
> Fix error callback issue

- README.md
- benchmark/index.js
- db.js
- indexes/full-mentions.js
- operators/index.js
- package.json
- test/basic.js
- test/createHistoryStream.js
- test/full-mentions.js
- test/migration.js
- test/multiple-indexes.js
- test/operators.js
- test/query-waits-migrate.js
Follow up to https://github.com/ssb-ngi-pointer/jitdb/pull/141. Also a **breaking change**.
> use jitdb@3 and where() operator

- compat/ebt.js
- test/basic.js
- test/ebt.js
1st test :x:, 2nd fix :heavy_check_mark:
> sbot.getAtSequence does an implicit onDrain 

- db.js
- test/basic.js
> Make sure addBatch updates state at the correct moment

- operators/index.js
- package.json
- test/basic.js
> add operator authorIsBendyButtV1()

- compat/log-stream.js
- db.js
- test/createLogStream.js
This one is also useful to add.
1st :x:, then :heavy_check_mark:
> support opts.reverse in createLogStream()

- db.js
- test/basic.js
Fixes a false positive "feed fork" error. Full context here: https://github.com/ssbc/ssb-ebt/issues/61
1st :x: , 2nd :heavy_check_mark:
> fix loadStateFeeds to call reEncrypt

- README.md
Add a link to ssb-browser-core to the readme
> explain run in a browser

- README.md
In the readme example. I think this is correct. Is it?
> show where keys come from

- README.md
For more documentation about how to use this. relevant to issue #282
> Add a link to dev.scuttlebutt.nz

- README.md
Should make it easier to get started using ssb-db2 for projects
> Add links to several secret-stack plugins that works well with db2

- README.md
This should fix #296. @nichoth
> Document onDrain

- README.md
I noticed this was not documented, so :)
> Document post

- README.md
> Document operators

- indexes/plugin.js
- test/index-upgrade.js
This PR should fix this [issue](https://github.com/ssb-ngi-pointer/ssb-db2/issues/302#issuecomment-1014674314). I could not find a test for the version upgrade functionality so wrote a test for that.
> Test that index upgrade works

- db.js
Continuation to #308. I couldn't find a test for these, but I can see that these changes "actually" fix the warnings I was seeing in manyverse.
> Improve db close logic

- db.js
- test/base-index.js
Writing tests in other libraries was getting tedious, so I copied functionality from https://github.com/ssbc/ssb-db/blob/4c8a8b503df80e407e4cfb0167633f39a4a3377b/index.js#L56-L60
Fixes issue #229
> add "temp" as an alternative to config.path

- compat/history-stream.js
- db.js
- package.json
- test/basic.js
- test/delete.js
This is to support the breaking change in jitdb 5.0
> Support sortBy in jitdb

- package.json
tap-spec is no longer maintained.
> Use tap-arc instead of tap-spec

- package.json
- status.js
Similar to https://github.com/ssb-ngi-pointer/jitdb/pull/201
> dont prune jit from status object

- README.md
- db.js
- test/basic.js
Just bubbling up https://github.com/ssb-ngi-pointer/jitdb/pull/202
> add prepare() API to call into JITDB

- db.js
- package.json
- status.js
- test/basic.js
See https://github.com/ssb-ngi-pointer/jitdb/pull/204
> improve progress calculation in status.js

- package.json
- seekers.js
- test/migration.js
Similar to https://github.com/ssb-ngi-pointer/jitdb/pull/211
> improve seekers so they always return numbers

- test/reindex-encrypted.js
Just refactoring a test to have less lines of code.
> refactor test with toPromise instead of toPullStream

- db.js
- indexes/keys.js
- operators/index.js
Just a cosmetic refactor to avoid duplicates of `parseInt(seqStr, 10)`
> refactor keys index getSeq()

- db.js
- indexes/about-self.js
- indexes/base.js
- indexes/ebt.js
- indexes/full-mentions.js
- indexes/private.js
- seekers.js
Similar to https://github.com/ssb-ngi-pointer/jitdb/pull/218
> Use bipf.seekKey2, a tiny bit faster

- indexes/keys.js
Did a grep and there was 1 seekKey left ;-)
> Use seekkey2 in keys index

- encryption-formats/box2.js
This is mostly a code cleanup by using the unbox function since we don't need the key here. There is also a tiny performance improvement because the derived secret is only calculated [once](https://github.com/ssbc/envelope-js/blob/8532da86ea84f79ae2532b17e2768586e1c40da6/unbox.js#L17)
> Use unbox function

- compat/history-stream.js
- db.js
- defaults.js
- package.json
- test/basic.js
- test/compaction-resume.js
- test/compaction.js
- test/createHistoryStream.js
Remove `post-compact-reindex-jit` state file from ssb-db2 and use what jitdb 7.0.0 has instead.
> use jitdb@7.0.0

- benchmark/index.js
I thought I was going to speed up `deleteFeed()` but I wanted to first make a benchmark to prove it's getting faster. Then I tried all sort of things and I realized I could only make `deleteFeed()` *slower* :cry: . But at least it's useful to add this benchmark so we know the baseline for deleteFeed.
> benchmark deleteFeed()

- core.js
This is so small and simple, that I doubted if I should ask for a review.
> reindex jitdb in reset()

- core.js
- test/basic.js
I'm trying to get a root msg in https://github.com/ssbc/ssb-tribes2/pull/29 but i have its id in uri form
> Accept URI IDs in get and getMsg

- nums-file.js
Discovered via a crash report in Manyverse.
> fix typo in NumsFile error handler

- core.js
> Batch 1000 to speed up reindexEncrypted

- core.js
- indexes/base.js
- log.js
- test/base-index.js
This should fix #395. The base index is both used for EBT & validation so doesn't make sense to update for ooo messages.
> Adding ooo messages should not update base index

- .github/workflows/node.js.yml
- README.md
- compat/db.js
- compat/ebt.js
- core.js
- indexes/base.js
- indexes/ebt.js
- indexes/full-mentions.js
- indexes/keys.js
- indexes/plugin.js
- indexes/private.js
- migrate.js
- nums-file.js
- package.json
Note! This makes ssb-db2 incompatible with any version of Node.js smaller than 16.x
I suppose we should mark this as a breaking change.
> replace clarify-error with new Error cause

- README.md
@mixmix can you see if this helps you describe what the function does?
> Improve documentation for getStatus
