README.md, compat/db.js, compat/ebt.js, compat/history-stream.js, compat/index.js, test/createHistoryStream.js
=> Move compat into its own folder and add examples to README

indexes/base.js, indexes/plugin.js, indexes/social.js
First I noticed that we could use `debug` with namespaces such as `"ssb:db2:stuff"`, which is standard practice in [debug](https://www.npmjs.com/package/debug), allowing us to filter them in runtime like this: `DEBUG=ssb:* node myapp.js` or `DEBUG=ssb:db2:* node myappjs`.
Then, I refactored a bit so that we can get rid of one argument out of the 8 (many!) arguments to `Plugin()`.
=> refactor usage of debug()

compat/ebt.js, compat/history-stream.js, db.js, indexes/base.js, indexes/partial.js, indexes/plugin.js, indexes/social.js, log.js, msg-utils.js, seekers.js, test/base-index.js, test/createHistoryStream.js, test/operators.js, test/social-index.js, test/validate.js
These are simple refactors, mostly just for my sanity as I try to navigate the codebase, hope it's useful:
- `require`s always at the top, unless needed for browser differentiation
- `const` preferred if we know we won't re-assign the thing afterwards
- `let` preferred over `var` (var allows you to do the declaration twice, allowing some sneaky bugs pass through sometimes)
- variables used in scope declared at the top, inner functions declared below that (see `db.js` for an example)
This PR doesn't contain anything else interesting other than code shuffling.
=> refactor: move lines around, use const/let

indexes/base.js, indexes/plugin.js, indexes/social.js
This is rather embarrassing, I was fixing a bug related to unwrittenSeq a while ago and accidentily broke the chunkSize mechanism so it was more or less writing the whole time. With this commit indexing is 3x faster. 
I did discover some thing while tracking this down: chunksize 512 seems pretty good, I tried other values. Also the decode part is a large part of the indexing. The overhead of level is not so bad.
=> Fix indexing performance by properly chunking writes

README.md, db.js, index.js, migrate.js, migration.js, package.json, test/base-index.js, test/createHistoryStream.js, test/migration.js, test/operators.js, test/social-index.js, test/validate.js
- Protect ourselves against forking when maintaining new log alongside old log
- "force only one source of truth"
- consider deleting the old log, or replacing it with broken data
=> migration plugin for ssb-db=>ssb-db2

db.js, indexes/base.js, indexes/social.js
I started by removing `query`, `fromDB`, `and` from the social index, and then realized there were other things not used. I'm pretty sure we are capable of bringing all these changes back, if in the future we realize we need them, but for now it seems better to not let dead code lying around possibly mistaken as important code.
=> remove unused code in the indexes

README.md, db.js, defaults.js, indexes/partial.js, indexes/plugin.js, log.js, migrate.js, test/migration-alone.js
=> Allow `migrate` to be included alone

indexes/social.js, operators/social.js, package.json, test/social-index.js
This depends on the [jitdb PR](https://github.com/ssb-ngi-pointer/jitdb/pull/38).
Allows the following kind of queries for all votes for a specific msg and all live updates:
```
db.query(
and(votesFor(postMsg.key)),
live(),
toPullStream(),
pull.drain((result) => {
})
)
```
=> Support live queries in social index

indexes/social.js
By having the key first instead of the type, level can store it smarter. With this simple change the index size of social goes from 35mb to 33mb. Indexing time is the same: 12s as is query time on the indexes.
=> Improve social index size by about 5%

indexes/plugin.js, indexes/social.js
One more of these *facepalm* bugs. With this, the index time of private (that I'm working on) goes down from 10 seconds to 2 seconds :-) And social from 12 to 7.
=> Don't run live stream until after we finish write the seq

migrate.js
This was necessary to solve some race conditions I got when putting this plugin inside Manyverse.
Specifically, the flumelog-offset existed (as a file) but was of empty size, and doing a `live` streaming on that caused a crash in flumelog-offset.
This PR does two things:
- `fileExists` checks both that it exists and size > 0
- some exponential backoff retries of the `migrate.start()` function, handling corner cases such as closing the sbot
Tested that it works in production in Manyverse
=> fix migrate plugin handling of old log existence

db.js
`./indexes/partial` imports `../waiting-queue` which doesn't exist, and this causes `noderify` to crash when building the backend in Manyverse.
I'd need this merged and released soon, if you can, @arj03
=> disable import of Partial

README.md, migrate.js, package.json
Since `migrate` is I/O bound, not CPU bound, pull-drain-gently never gains us much, so I'd like to remove it to simplify the codebase. Should be easy to add back if we ever need it again. See also the other refactor commit contained here
=> Remove pull-drain-gently

db.js, indexes/base.js, operators/index.js, package.json, seekers.js
This converts one of the level db indexes to a prefix index. I ran a test where I removed all indexes and lets it run followed by a query for a specific key. 
```
battery old: 53.2 s
arj@arj:~/dev/ssb-db2$ du --si ssb/db2/indexes/*
130M	ssb/db2/indexes/base
4,1k	ssb/db2/indexes/canDecrypt.index
529k	ssb/db2/indexes/encrypted.index
31M	ssb/db2/indexes/social
battery new: 51.7 s
arj@arj:~/dev/ssb-db2$ du --si ssb/db2/indexes/*
30M	ssb/db2/indexes/base
4,1k	ssb/db2/indexes/canDecrypt.index
529k	ssb/db2/indexes/encrypted.index
6,4M	ssb/db2/indexes/key.32prefix
6,4M	ssb/db2/indexes/offset.index
6,4M	ssb/db2/indexes/sequence.index
34M	ssb/db2/indexes/social
13M	ssb/db2/indexes/timestamp.index
```
While the speed up is not that big, one has to consider that the second had to create the jitdb …
=> Convert key index in base to an jitdb prefix index

operators/index.js
Just a refactor, not too important, and requires a reindex, but I figured that more descriptive/explicit is better for our future sanity and other developers, and this is not yet used in production, so now is the time to do this kind of refactor.
E.g. imagine if in the future we add another kind of of `private` e.g. `value.content.private`, then it makes it very clear what is what by making it explicit from day one.
=> refactor indexType names

operators/index.js
I ran this example:
```js
const results = await sbot.db.query(
and(
mentions('@QlCTpvY7p9ty2yOFrv1WU1AE88aoQc4Y7wYal7PFc+w=.ed25519'),
isRoot(),
channel('scuttlebutt')
),
toPromise()
)
```
and my computer crashed again, I think it has the same memory leak cause. But the news is that I also realized that it didn't complete the query within 40 seconds (database had a log.bipf but indexes folder was empty), but instead keep on running. I looked into the profiler and apparently `matchAgainstPrefix` was taking a long time (notice the right side of the picture):
This happens because there are lots and lots of false positives that `matchAgainstPrefix` has to go through, so I think we lose the benefit of prefix. Then, I removed the prefix (see the git diff), and the result looks like this …
=> dont use prefix for isRoot()

db.js, indexes/base.js, indexes/mentions.js, indexes/plugin.js, indexes/private.js, test/base-index.js, test/createHistoryStream.js, test/ebt.js, test/mentions-index.js, test/operators.js, test/validate.js
The idea here is that instead of each plugin doing their own log stream we can have one stream driving them all. The improvement is substantial as was known from db1 and documented in #54. And the gain will only grow as new indexes are added. An added benefit is that with this we can merge #58 because in the case of a crash where base is then ahead of private, this will make sure that we continue from where private stopped. The overhead of calling the calls for indexes that are already up to date is minimal. Also because the indexes are pretty fast already, adding a new overhead will just give a 5 seconds delay before the normal indexes will start received new data.
=> Use one log stream for all indexes

indexes/private.js
`atomically` behaves weirdly, and probably needs to be fixed:
Check https://github.com/fabiospampinato/atomically/blob/799d961964a27383f61a349af6d4a8e00c3b8395/src/utils/scheduler.ts#L48
If you call `write` many times synchronously (or "fast"), it just piles up a bunch of functions in this scheduler, and for some reason this logic only releases the queue of functions... when the queue is size 1. :sweat_smile: So it kept growing to thousands and thousands...
We should probably fix that, but a simple fix for now, which anyway made sense even if we didn't have a memleak, was to throttle the writes to the filesystem. These `saveIndexes` calls were super frequent, probably a bad idea:
```
/home/staltz/.ssb/db2/indexes/encrypted.index 	 12178 // size of atomically scheduler
saveIndexes at …
```
=> fix memory leak

db.js, indexes/base.js, indexes/mentions.js, indexes/plugin.js, indexes/private.js, package.json
`p-defer` is a ~6 LOC dependency. The approach here is to introduce a `stateLoaded` deferred promise (think: an Obv that can only be `set` once) instead of piggybacking on `seq`, and then collect all `stateLoaded` for all indexes using Promise.all
=> replace setTimeout in onIndexesStateLoaded with promises

indexes/plugin.js
The official API for checking if level is closed is https://github.com/Level/level#dbisclosed
I ran the tests 100 times and couldn't bump into #35 anymore. Still not sure if this is a definitive solution though
```
for i in $(seq 100); do npm test; sleep 1; done
```
=> use official leveldb isClosed() API

compat/history-stream.js, db.js, operators/full-mentions.js, test/base-index.js, test/createHistoryStream.js, test/full-mentions.js, test/migration.js, test/operators.js
Implementation comments are inline in the code
```
➜  ssb-db2 git:(master) rm -rf ~/.ssb/db2/indexes
➜  ssb-db2 git:(master) node gitignored/example.js
There are 15 messages
duration: 22285ms
➜  ssb-db2 git:(master) node gitignored/example.js
There are 15 messages
duration: 419ms
➜  ssb-db2 git:(master) node gitignored/example.js
There are 15 messages
duration: 401ms
➜  ssb-db2 git:(master) node gitignored/example.js
There are 15 messages
duration: 402ms
➜  ssb-db2 git:(master) du -h ~/.ssb/db2/indexes
7,6M	/home/staltz/.ssb/db2/indexes/base
29M	/home/staltz/.ssb/db2/indexes
```
```
➜  ssb-db2 git:(ondrain) rm -rf ~/.ssb/db2/indexes
➜  ssb-db2 git:(ondrain) node gitignored/example.js
There are 15 messages
duration: 20885ms
➜  ssb-db2 git:(ondrain) node gitignored/example.js
There are 15 …
```
=> Implicit onDrain() when using db.query()

log.js, package.json
This uses the new functionality in async-flumelog to better guard against file corruption by trying to fix the latest block on load
=> Validate latest block in log on load

README.md, db.js, test/validate.js
I wanted to add documentation to our methods and started looking at add. I never really used the method in ssb-browser only internally, but noticed that in ssb-db it validates. I didn't want to change for no reason, so moved some things around a bit and made it so that `add` works like in ssb-db. I still want to have a look at #7, but for now this should be good enough.
=> Better documentation

migrate.js, test/migration.js
For issue #95. I tested this in my production Manyverse and it gave a significant improvement. Time between "press like" and "like appears" dropped from (approximately) 45 seconds to (approximately) 2 seconds.
This PR has a somewhat hacky solution. It basically expects `sbot.get(msgkey, cb)` to call the `cb` with 3 arguments, `cb(err, msg, offset)`. If the 3rd argument is undefined, migrate plugin fallsback to what it was doing before: scan the new log, counting the records, then scan the old log.
If `sbot.get` is patched to provide the offset in the third arg, this improves performance a lot. Otherwise, it's the same. I intend to ship a hacky `ssb-db` to provide the third arg. We can work in the `ssb-db` repo to add this support, or add another API, either way, we can rather easily get …
=> improve performance of migrate plugin

db.js, test/validate.js
This should fix #102 and #7.
ssb-validate knows the state of each feed, so if you add the same message twice or a message not in order it will error. We can rely on this and only check if message already exists in the strict OOO case.
I also reworked addOOOStrictOrder so that it doesn't touch the internal validate state.
=> Faster add and better addOOOStrictOrder

benchmark/index.js
We're using the "inefficient mode" of migrate plugin because https://github.com/ssbc/ssb-db/pull/319 is not yet deployed, so the `initial indexing` benchmark is disturbed by migrate running in the background (it's not actually migrating anything, it's just scanning the entire old log). Once we have efficient mode for migrate, then we *could* keep this line of code in, but anyway it doesn't make sense to keep it in.
=> benchmark: dont migrate during initial indexing

benchmark/index.js, package.json
A bunch of updates:
- Benchmark migrate operating alone (no db2, no db1)
- Benchmark migrate operating with db1, using its APIs
- Report in markdown table, not a markdown list
- Add some setTimeout 500ms to create some "silence" and make it easier to detect what is what in the Chrome profiler
- Use async/await to manage all these timeouts more sanely
- The DeferredPromise is unfortunate, but when you use `async (t) => {` with Tape, it ends the test once it reaches the end of the function, I needed a way to prevent that
=> benchmark: two different types of migrate

indexes/plugin.js
As it is now, when the normal log finishes processing, all indexes will get a [write](https://github.com/ssb-ngi-pointer/ssb-db2/blob/05a7779953c22fae7846c05e113d5fb16b022c28/db.js#L263). If an index doesn't write something for each message, lets say its only interested in a particular type, then the last write might not write the final offset which means that you can't do something like onDrain on that index. Furthermore when you restart the app, it has to go through all those messages again it just checked. In the live case we have the same problem, but here we don't want to write for each message so we debounce the write a bit.
=> Always keep track of latest offset

db.js, migrate.js, package.json
Sent as a PR just to make sure we don't concurrently do the same thing.
Also updates AAOL
=> Release 0.17.0

operators/index.js, package.json
Before and after of the perf benchmarks:
```diff
migration (using ssb-db)
✔ delete db2 folder to start clean
✔ ssb-db has finished indexing
-   ✔ duration: 2816ms
+   ✔ duration: 2870ms
fallback to close
migration (alone)
✔ delete db2 folder to start clean
-   ✔ duration: 2705ms
+   ✔ duration: 2722ms
initial indexing
✔ null
-   ✔ duration: 2008ms
+   ✔ duration: 2043ms
setup
key one initial
-   ✔ duration: 454ms
+   ✔ duration: 464ms
key two
-   ✔ duration: 19ms
+   ✔ duration: 20ms
key one again
-   ✔ duration: 14ms
+   ✔ duration: 15ms
latest root posts
-   ✔ duration: 371ms
+   ✔ duration: 364ms
latest posts
-   ✔ duration: 29ms
+   ✔ duration: 32ms
votes one initial
-   ✔ duration: 355ms
+   ✔ duration: 383ms
votes again
-   ✔ duration: 11ms
+   ✔ duration: 0ms
hasRoot
-   ✔ …
```
=> some operators use useMap and prefix

db.js
Similar to `ssb:db2:migrate:progress`. I thought that this number crunching would be likely needed in many apps, so better to put it here. If people want more precise numbers, per index, they can use `getStatus`.
=> emit event ssb:db2:indexing:progress

compat/history-stream.js, package.json, test/createHistoryStream.js
1st adds failing test, 2nd commit fix.
We need this because ssb-replicate/legacy does a hook on the history stream.
=> add test for hookable createHistoryStream

benchmark/index.js, package.json
`.rss` covers everything, while `.heapTotal` is just objects, arrays, strings, buffers, things like that. I believe we have a LOT of data put in the stack, because we heavily rely on small numbers and small strings.
I checked in `htop`, both desktop and mobile (yeah you can do `htop` in Termux on Android) and memory usage of Node.js on desktop and of Manyverse on Android (using the latest ssb-db2) float around half a gigabyte.
=> report full memory usage in benchmarks

db.js, test/basic.js
This fixed the problem found in https://github.com/ssbc/ssb-friends/pull/49. Namely that we don't wait for the state to be loaded, so we end up with the wrong validate. Only publish and add really need this anyway which is why they are the only ones with this check.
=> Fix add/publish so we wait for the state to be loaded

benchmark/index.js, log.js, migrate.js
Adds new API:
- `sbot.db2migrate.stop` (needed for one new benchmark)
Adds new benchmark tests:
- Run migrate together with db1 and db2
- Run migrate and db2, but no db1
- Run migrate and db2, continuing from a 90%-completed previous migration, to test migrate's `findMigratedOffset` function
Optimizes migrate's `inefficientFindMigratedOffset`:
- This was doing a log.stream, but it never read the contents of the records, so this PR adds a `decrypt: false` opt that bypasses private.decrypt
- Even though private.decrypt has some checks that skip the majority of unbox calls, this new optimization skips the unbox call also when the msg is intended for the author (i.e. canDecrypt)
- This improves the "Migrate continuation (+db2)" benchmark run by -15%
=> add benchmarks for all migrate situations

indexes/base.js, indexes/ebt.js, indexes/full-mentions.js, indexes/plugin.js, package.json, test/multiple-indexes.js
Fix #167. It turns out that full mentions was using this processed. So it was buggy before. I added a test to show that it was buggy before, but is now working. Also makes the indexes not have to do the "can I use this" check.
=> Fix processed

indexes/about-self.js, test/about-self.js
It wouldn't make sense to make an operator, because profiles are reduced state (not ssb msgs), so we couldn't use the JITDB way. Instead, I made a new method getLiveProfile that just reads from pull-level
=> add method getLiveProfile to about-self

README.md, benchmark/index.js, compat/ebt.js, db.js, indexes/about-self.js, indexes/base.js, indexes/ebt.js, indexes/full-mentions.js, indexes/plugin.js, package.json, test/about-self.js, test/full-mentions.js, test/query-waits-migrate.js
This is a bit debatable PR, because it's a big refactor the plugins. But I'd like to explain the purpose: basically to simplify plugin creation, not just for us, but specially for other developers in the future. I didn't bring this up in our call because I suddenly thought about trying this. :)
Plugin developers had to be conscious about several details: must remember to put `close: level.close.bind(level)` at the bottom, must re-export fields like `onData` and `writeBatch` even if the new plugin doesn't call these things, and overall there's some duplicate code going on.
I thought about what to do here (not just today, I've been thinking about this randomly in the past weeks), and I think this is where OOP and inheritance helps. I don't mind the closure and `this`less pattern, I'm fine …
=> Refactor plugin pattern as OOP

indexes/base.js, test/basic.js
The tests are wrong in one spot, see this comment: https://github.com/ssb-ngi-pointer/ssb-db2/pull/179#issuecomment-779356642
Also, besides the tests being wrong, also so was the implementation of delete. I don't have proof in the tests, but you can easily confirm this by yourself by putting some console.logs here and there: the `level.del` happens **1st** and **then** our batch system kicks in, **re-adding** the item that should be deleted.
This PR adds a commit that fixes the delete, to flush first. This will cause tests to fail. Then, I'll fix the test.
=> before deleting index item, must flush batch

benchmark/index.js, package.json
- add benchmark for indexes folder size
- fix benchmark for memory usage without indexes 
- It was measuring slightly at the wrong time, we want it to measure when db2 is running light (or none) workloads of migrate, and no indexes
=> Benchmark disk

compat/db.js, compat/index.js, test/compat.js
This was missing, it's needed in https://github.com/staltz/ssb-lan/blob/230daca3df3d00742d31938b398dcb9a212da031/src/index.ts#L95 and in db1 it's defined here https://github.com/ssbc/ssb-db/blob/8312ebe7df1b2b4e3282f75c73c753d8bc425dae/index.js#L122
=> add sbot.keys in compat

db.js, indexes/base.js, test/createLogStream.js
The "delete all" test was sometimes failing. It makes sense that `removeFeedFromLatest` needs a callback.
=> fix flaky test "delete all"

defaults.js, log.js, migrate.js, package.json
I admit I made PR #185 before, and then closed it, but I'm rerunning experiments here on my phone, and this definitely gives users control over the UI. It will be useful to allow users to navigate the UI, discover what's going on, read progress reports, etc, as opposed to feeling like the app died (when in reality it is doing useful work as fast as it can).
It will have a sizable impact on total migrate duration but as I outlined in #193, I think it's some apps will benefit from doing it gradually.
=> use pull-drain-gently in migrate

migrate.js, package.json
The changes I made to asyncAOL's log.stream make one test (migrate) not pass anymore.
=> update async-append-only-log to 3.0.5

compat/index.js, index.js
`compat/index.js` was calling only the `init()` of each child plugin, this was skipping all the `manifest` and `permissions` that they were declaring.
=> use array shape for secret-stack plugins

test/about-self.js, test/compat.js, test/createLogStream.js, test/ebt.js, test/full-mentions.js, test/migration.js, test/operators.js
One error I was seeing often was
```
Error: Closed
at Request._openAndNotClosed (/home/staltz/oss/ssb-db2/node_modules/.pnpm/random-access-storage@1.4.1/node_modules/random-access-storage/index.js:180:38)
at Request._run (/home/staltz/oss/ssb-db2/node_modules/.pnpm/random-access-storage@1.4.1/node_modules/random-access-storage/index.js:203:16)
at drainQueue (/home/staltz/oss/ssb-db2/node_modules/.pnpm/random-access-storage@1.4.1/node_modules/random-access-storage/index.js:246:48)
at Request._unqueue (/home/staltz/oss/ssb-db2/node_modules/.pnpm/random-access-storage@1.4.1/node_modules/random-access-storage/index.js:167:23)
at Request.callback (/home/staltz/oss/ssb-db2/node_modules/.pnpm/random-access-storage@1.4.1/node_modules/random-access-storage/index.js:172:8)
at onclose …
```
=> increase timeouts in several tests

compat/ebt.js, db.js, migrate.js, utils.js
Tested on my manyverse and didn't get #207 symptoms anymore. 
Ideally, it would be good to have tests for this, but it's quite a lot of work to setup everything to reproduce it (would require migrating a fixture, then replicating with some peers which have more data on that fixture). Doable, but I'm on a deadline.
Some more comments inline
=> recalculate ssb-validate state when migrate ends

benchmark/index.js, package.json
I noticed we didn't have a benchmark of simply adding a bunch of messages. This is useful for testing stuff like how fast can we add 1000 messages coming from EBT.
=> Add test for adding a bunch of messages

README.md, db.js, test/base-index.js, test/private.js
To fix #211. Current behaviour can be a bit of a gotcha when coming from db1. First commit is just a failing test.
=> Auto encrypted publish when recps is set

indexes/private.js, package.json
Similar to the [PR](https://github.com/ssb-ngi-pointer/jitdb/pull/153) in jitdb. This is just a replace with another library. Also depends on this [PR](https://github.com/ssb-ngi-pointer/atomic-file-rw/pull/2) in atomic-file-rw hence the draft status.
=> Replace atomically-universal with atomic-file-rw

db.js
Was testing rust validation and discovered that we using the ssb-validate in a suboptimal way. Basically recalculating the hash of the messages.
Before:
```
add a bunch of messages
✔ duration: 361ms
```
After:
```
add a bunch of messages
✔ duration: 292ms
```
bunch=1000.
=> Faster validate on add

compat/db.js
We were debugging https://github.com/ssb-ngi-pointer/go-ssb-room/issues/190 and figured that if `pull.drain` receives an ending-error and doesn't have the `done` callback in `pull.drain(cb, done)`, then it throws the error. `throw err` is dangerously in that it may crash the app.
ssb-db2's compat layer implements `createWriteStream`. While the only known usage of `createWriteStream` is ssb-replicate [which provides a `cb`](https://github.com/ssbc/ssb-replicate/blob/7567b077ade9350e287ae8d3a08a84ae84d8498b/legacy.js#L271) and thus should not trigger the `throw err` in `ssb-db2/compat/db`, it is still safer to handle this error in a non-crashing way, in case someone else uses `createWriteStream` without passing a callback.
Avoid `throw err`, use `console.error` instead.
=> log createWriteStream errors instead of throwing

db.js, test/ebt.js
While testing unbermuda I noticed that something was up with EBT.
EBT on startup gets the [latest state](https://github.com/ssbc/ssb-ebt/blob/master/index.js#L81) and then maintains the state using [post](https://github.com/ssbc/ssb-ebt/blob/master/index.js#L87). It even uses this (internally)[https://github.com/ssbc/ssb-ebt/blob/master/index.js#L74] to manage state. The problem would manifest itself in EBT when having multiple EBT connections, then you would receive too many messages because the clock is not properly kept in sync. The problem could also be triggered by something other than EBT writing messages (which is how I found this problem).
DB1 called post on [both](https://github.com/ssbc/ssb-db/blob/b2256fd7e3e6e3804ca5f388b3fc351312250d05/minimal.js#L111) `add` and `publish`. 
I …
=> Call post on add functions like publish does

db.js, test/migration.js
So I was hunting down the [flaky bug](https://github.com/ssb-ngi-pointer/ssb-meta-feeds/issues/13) in ssb-meta-feeds tests. What I was seeing was that it was failing the restart test. The reason it was failing the restart test was because the save function in private saves every [1 second](https://github.com/ssb-ngi-pointer/ssb-db2/blob/b918e59bd31fa60392b17276aa4b0d3b751feb83/indexes/private.js#L88) while other indexes more often. And that meant that once the restart test started up, there was no private index. This shouldn't have been a problem as it should have been regenerated before the query ran, but the `updateIndexes` function had a bug where it did not take into account the private index, which meant that the decrypt function in the private index was given a starting point that …
=> Fix updateIndexes to account for private index progress

README.md, db.js, package.json, test/validate.js
This is my review of https://github.com/ssb-ngi-pointer/ssb-db2/pull/236. I have put it into ssb-browser and did quite a few tests. Initially I had the same `asyncMap(sbot.db.add)` so that part was really slow like the tests. Not sure how to best avoid that gotcha. 
It is probably easiest to read this as the individual commits, the first two are rather simple. The next 2 is about making sure that post.set works correctly in all cases. post.set is used to "communicate" with ebt and before there was a bug where `addBatch` did not call `post.set`. Furthermore the ooo methods must never call that function, unless they are at the head of the feed (this is why I added setPost, secretstack seems to hook that object / function into oblivion). In general I'm not super happy about the way this post …
=> Validate2 review changes

README.md, db.js, indexes/private.js, test/basic.js, test/ebt.js
@arj03 This PR targets `publishAs-simple` because I didn't want to push to that branch directly. Reviewing commit-per-commit is probably easiest.
This PR surprisingly is *removing* support for bendy butt in `publishAs()` but bear with me: I progressively realized that "wait, we don't need this" and then "we don't need that either", and deleted code until it got to this state.
If we put bendy butt validation in `publishAs()` (as the FIXME said) **and** implement support for bendy butt in `add()`, the two functions end up looking exactly the same (for the bendy butt part), and that's because both of them accept a `msgVal`, validate it, update state, and add it to the log.
So I removed support for bendy butt in `publishAs()`, and when you think about it, it makes sense because the bendy butt …
=> Remove publishAs() for meta feeds

package.json
You can see I discovered a new toy
```
npm notice 
npm notice 📦  ssb-db2@2.1.5
npm notice === Tarball Contents === 
npm notice 1.5kB  .github/workflows/node.js.yml
npm notice 17.1kB benchmark/index.js           
npm notice 643B   compat/db.js                 
npm notice 852B   compat/ebt.js                
npm notice 1.9kB  compat/history-stream.js     
npm notice 118B   compat/index.js              
npm notice 1.3kB  compat/log-stream.js         
npm notice 2.3kB  indexes/about-self.js        
npm notice 2.5kB  indexes/base.js              
npm notice 1.3kB  indexes/ebt.js               
npm notice 2.0kB  indexes/full-mentions.js     
npm notice 780B   indexes/keys.js              
npm notice 4.1kB  indexes/plugin.js            
npm notice 4.4kB  indexes/private.js           
npm notice …
```
=> add package.json files field

compat/db.js, compat/feedstate.js, db.js, test/feedstate.js
Context: I'm interested in getting [ssb-crut](https://gitlab.com/ahau/ssb-crut) working with ssb-db2 so that we can use that for a building a library that implements the fusion identity spec.
I already have a branch that makes the library compatible with ssb-db2 I have been waiting with opening this PR until the validate2 branch was merged.
=> Add more db1 compability methods

utils.js
If you go to `ssb-meta-feeds-rpc` right now and run `npm it`, the test gets stuck. It's related to one of the these `onceWhen` not continuing.
I think the underlying problem is in `obz`, as a concurrency bug when it loops through current listeners, but I spent some time trying to make a simple test and didn't manage to reproduce a clear error case. 
On the other hand, `onceWhen` is written in a way that triggers the bug in `obz`, so we can rewrite `onceWhen` to not trigger the bug. The culprit is the `remove()` call, it synchronously messes up with the for-loop of current listeners. So we just schedule to run the `remove()` later. Anyway, the point of `remove()` is merely to avoid wasting computation. If we never `remove()`, the functionality would still be fine, because we have an `if …
=> fix onceWhen self-remove logic 

operators/index.js, test/operators.js
To solve issue https://github.com/ssb-ngi-pointer/ssb-meta-feeds-rpc/issues/9 in [ssb-meta-feeds-rpc](https://github.com/ssb-ngi-pointer/ssb-meta-feeds-rpc), we need to update [ssb-subset-ql](https://github.com/ssb-ngi-pointer/ssb-subset-ql) to use a non-dedicated index for `value_content_type`, and in turn that requires adding this functionality to ssb-db2.
=> allow type() operator to be non-dedicated

db.js
I sometimes got this kind of error, which seemed non-fatal but would cause the `sbot.close.hook` to not proceed:
```
(node:51671) UnhandledPromiseRejectionWarning: Error: async-flumelog: closed
at async-append-only-log/index.js:308:36
at async-append-only-log/index.js:341:69
at Object.onDrain (async-append-only-log/index.js:317:12)
at close (async-append-only-log/index.js:306:10)
at async-append-only-log/index.js:317:12
at promisify-4loc/index.js:3:11
at new Promise (<anonymous>)
at promisify-4loc/index.js:2:3
at ssb-db2/db.js:494:39
(node:51671) UnhandledPromiseRejectionWarning: Unhandled promise rejection.
This error originated either by throwing inside of an async function 
without a catch block, or by rejecting a promise which was not handled with 
.catch(). To terminate the node …
```
=> fix UnhandledPromiseRejectionWarning on close()

compat/log-stream.js, test/createLogStream.js
1st commit adds a failing test, 2nd commit fixes the test.
For netsim we need go-ssb, ssb-js with ssb-db, and ssb-js with ssb-db2 to behave similarly. 
go-ssb and (js) ssb-db support the opts.limit arg in createLogStream, but ssb-db2 doesn't.
Add opts.limit in createLogStream
=> support opts.limit in createLogStream()

README.md, db.js, log.js, package.json, test/basic.js
This exposes the recently added transaction support in AAOL. I thought it would be fine that this just worked on classic messages. We can always add bendy butt if needed. Similar to addBatch.
=> add addTransction() functionality

db.js
Adds a `debug` message to `addImmediately()` to report when validation fails for a bendy butt message.
**Example output**
`2021-10-06T13:59:26.650Z ssb:db2 validation failed for bendy butt message in addImmediately(): invalid message: signature must correctly sign the payload`
**Question**
Do we want to add any additional `debug` message while I have this PR open?
=> Add debug msg for bendy butt validation failure

db.js
Adds a `debug` message to `addImmediately()` to report when validation fails for a classic message.
=> Add debug msg for classic validation faliure

package.json
It's used in db.js, and when installing ssb-db2 with other package managers like pnpm, multicb would be missing if it's a dev dep.
=> multicb is a dependency, not dev dep

db.js, package.json
I was testing a client with private groups and ran into an issue where own key was not provided. This together with latest ssb-db2-box2 provides a better error and I wanted to let that error show up in cb instead of having client handling the throw. With this merged tests on ssb-db2-box2 should [work again](https://github.com/ssb-ngi-pointer/ssb-db2-box2/runs/4115715159?check_suite_focus=true). 
Note the bump of ssb-db2-box2 is not strictly needed as we just use it for benchmarking, but thought it would be good to have that the latest version anyway.
=> Handle exceptions from box2 as err cb instead of throwing

db.js, package.json
This is the problem I was experiencing with box2. Bendy butt was working fine, but not classic messages. The problem was the for classic messages we always used config.keys as the author, which doesn't work for metafeeds. So I had to change the api to make it work: https://github.com/ssb-ngi-pointer/ssb-db2-box2/commit/9c82d1909746327182511a0b8effd81de332ca3d. This PR uses the new api. With this change the tests will pass in ssb-db2-box2.
=> Fix box2 classic encryption for publishAs

indexes/private.js
Testing box2 for real now with private groups and ran into this bug.
I'll be pushing up a new test in ssb-db2-box2 that shows the problem. There is probably also a fix in jitdb needed for that test to pass.
=> Fix canDecrypt when reindexing decrypted messages

operators/index.js, package.json
These are the changes needed to make this module work with the bipf changes in jitdb. Note this also unpins bipf. The changes are almost trivial and is a good way I think to show that the jitdb PR is a sound approach.
This is still a draft PR as it depends on the jitdb PR: https://github.com/ssb-ngi-pointer/jitdb/pull/182
=> Work with latest jitdb bipf values change

log.js
To fix #292. My understanding is that this should not have any performance overhead compared to earlier versions.
=> (and in darkness) bind write to make sure `this` works

indexes/plugin.js
From https://github.com/ssb-ngi-pointer/ssb-db2/issues/291#issuecomment-998773451. I believe this should fix off-by-x bugs in level indexes. 
From that comment:
Look at this [line](https://github.com/ssb-ngi-pointer/ssb-db2/blob/86d502f0846c3c234f5f6ff47be3f5e4bbe58c20/indexes/plugin.js#L88) and imagine we have added a new plugin. In this case we will reindex, but most plugins will just [skip](https://github.com/ssb-ngi-pointer/ssb-db2/blob/86d502f0846c3c234f5f6ff47be3f5e4bbe58c20/indexes/plugin.js#L83). BUT they will update their `processedOffset` thus *lovering* it compared to `processedSeq`. If you then kill the app while some of them have updated, but *NOT* keys or base then there will be a mismatch!
=> Make sure processedOffset is only updated together with processedSeq

db.js, test/basic.js
When Manyverse is closed, I notice an error from here: https://github.com/staltz/manyverse/blob/332deeec5dca6166dcb39207e7581190ed1d5367/src/backend/plugins/connUtils.ts#L38
This error is silent and there are no problems for users, but I figured it would be good to fix that error anyway.
If `onDrain` is requested after the sbot (and ssb-db2) has been closed, we still seem to call the `cb`, even though the `cb` cannot and should not make use of any ssb-db2 APIs because the log is closed, indexes are closed, etc.
Add a boolean variable `closed` and check that it's false whenever calling the `cb`.
1st :x:, 2nd :heavy_check_mark:
=> when db is closed, dont call onDrain callbacks

benchmark/index.js, db.js, migrate.js, package.json, test/migration-alone.js, test/migration.js
Using EventEmitter for migrate "progress" events is heavy, see: https://github.com/ssb-ngi-pointer/ssb-db2/pull/201
There is no real need for the stream of progress events to be on the `sbot` as a stringly-named event. We can use pull-notify instead, which should be more straight to the point and hopefully a bit lighter.
**Note** this is a breaking change and will cause ssb-db2 version 3.0.0 to be published.
=> replace EventEmitter with pull-notify

README.md, benchmark/index.js, indexes/private.js
Decrypting box1 messages is quite heavy (I ran a local query here on a 1GB file, querying for all messages from a particular ID is 41 sec with decryption and 30 sec without). Especially for new users where out of roughly a million or so messages, more than 10% will be encrypted. For a new user joining the network they will never be able to decrypt these messages, so it would make sense to allow one to only start a certain time. Like from your first message. That was my first solution, but I realized that figuring out when the first message is from can be problematic. You might be reinstalling from a backup keys, or even if you have a database, just figuring out when the first message is from without building the indexing.
Instead I thought we could at least have a simple timestamp that …
=> Add startDecryptBox1 config

db.js, package.json
#320 
This is the final piece of the puzzle for stable progress bars in Manyverse, I tested these changes already in the app.
`prepare()` is doing `onDrain()` which means we're waiting for the base (leveldb) index to be built *before* starting the JITDB prepare.
Not only is this unnecessary (JITDB prepare is entirely independent from base index), it would also cause a jump backwards in the progress calculations, because first the leveldb indexes would be built (progress bar going forwards), and then once done the status update for JITDB would appear at the start (progress bar going back).
Don't do `onDrain()`.
I tried to write a test to catch this use case, but couldn't find a way.
=> prepare() should not wait for base index

status.js
**Problem:** when the log is empty, `stats.jit` is still considered at "100%" while all the leveldb indexes are considered at "0%", so averaging them would give something like "10%" stuck.
**Solution:** if the log is empty, just return 100% progress.
=> calculate progress when log is empty

db.js, indexes/about-self.js, indexes/base.js, indexes/ebt.js, indexes/full-mentions.js, indexes/keys.js, indexes/plugin.js, package.json, seekers.js
This is what I have used to test https://github.com/ssb-ngi-pointer/jitdb/pull/208. So not really ready yet.
Also we can do the same trick here for level indexes :)
=> Support passing in pValue

.gitignore, package.json
@arj03 This coverage allowed me to check that we don't have currently tests for `reindexOffset`, and that it seems like we need to update the implementation anyway, because it calls `processRecord` (not `onRecord`) and doesn't pass pValue. I'll work on that next.
=> add code coverage

db.js, indexes/plugin.js, package.json, test/reindex-encrypted.js
Working on https://github.com/ssb-ngi-pointer/jitdb/issues/199
There are no tests for reindexEncrypted in this repo, and as a result we were using the `processRecord` API incorrectly (not passing pValue arg), and even though we processed records on leveldb indexes, the changes were not persisted to disk.
I copied the test from ssb-db2-box2, but tweaked it to make sure that we query a leveldb index before and after reindexEncrypted. Also, after reindexOffset is called for all leveldb indexes, force flush to disk. 
=> force flush after reindexEncrypted is done

db.js, package.json, test/basic.js, test/delete.js, test/private.js, utils.js
Uses `jitdb.lookup()` (see https://github.com/ssb-ngi-pointer/jitdb/issues/215) to improve the performance of `del()` and `getMsg()`.
See the numbers for `del()`:
|  | Duration |
|--|--|
| Publish 1000 messages | 359.185ms |
| Delete 500 messages | 1039.531ms |
|  | Duration |
|--|--|
| Publish 1000 messages | 350.658ms |
| Delete 500 messages | 36.623ms |
| Wait for deletes to flush | 264.364ms |
Note that the flushing of deletes (264ms) is probably dominated by the duration of the [debounce period which is 250ms](https://github.com/ssb-ngi-pointer/async-append-only-log/blob/bec87f28c0f9a3e165fd36f98c8d3ba5622a40d4/index.js#L277).
=> improve performance of del() by 20x

README.md, db.js, defaults.js, indexes/about-self.js, indexes/base.js, indexes/plugin.js, indexes/private.js, package.json, test/compaction-resume.js, test/compaction.js
Context: https://github.com/ssb-ngi-pointer/ssb-db2/issues/306 and https://github.com/ssb-ngi-pointer/jitdb/issues/199
This PR adds the `compact()` ("async") API to ssb-db2 which just triggers async-append-only-log `compact()`. When it's done, it will rebuild all leveldb indexes from scratch, rebuild private indexes, and partially rebuild jitdb indexes. This is all done in a way that is crash-resistant, capable of resuming where it had stopped. And compaction is guaranteed to not happen concurrently with log.stream that builds indexes, or any jitdb query.
=> add compact() API and auto-rebuild indexes

indexes/base.js, test/basic.js
**Context:** I have an idea for deleting blocked feeds in an automatic way: use `ssb-friends` to scan all the blocked feeds and call `deleteFeed` on them. In case those feeds were already deleted, we need to make sure that `deleteFeed` is going to be performant and not cause any bugs.
**Solution:** when clearing the `base` index, this PR now checks first if an entry exists for that `feedId`. If it exists, then we can avoid calling `flush` and `level.del` in vain. 
An important thing to keep in mind is that `deleteFeed` is not atomic. The app may crash in the middle of a `deleteFeed`, meaning that some messages owned by that feed are deleted, but not all of them. So in a sense it's desired to call `deleteFeed` every time the app is opened, to make sure all messages are deleted.
Check more …
=> make sure that deleteFeed is idempotent and performant

indexes/ebt.js, log.js
There is no need to first decrypt the message and then reEncrypt them ;)
There is a test [here](https://github.com/ssbc/ssb-db2/blob/c35306e265ee67b60a87a355a992ebd9880d6f90/test/ebt.js#L78) for that case. Just so we are sure this is not breaking anything.
=> Faster ebt for encrypted messages

feed-formats/buttwoo-v1.js, log.js
Before: 494.17ms
After: 479.41ms
Biggest problem was that previous MsgIdBFE was not cached, so that had to be recalculated
=> Faster buttwoo validate

core.js, feed-formats/buttwoo-v1.js, log.js
`add()` is used in EBT so should be as fast as possible, this avoids some overhead. classic add goes from 8400 to 8800 with this change.
=> Faster single add

indexes/plugin.js, test/compaction.js
Working on putting compaction, deletes, truncation in Manyverse and noticed some issues related to compaction, such as
#355 
Update an index's `offset` obz as soon as reset() is called, so that subsequent onDrain() calls for that index use the updated `offset` value to know whether or not the indexing has completed.
=> fix Plugin.reset() logic to update offset

migrate.js, test/migration-alone.js
I was testing Manyverse, and noticed that right after it migrates `~/.ssb` to ssb-db2 (using `ssb-db2/migrate` *without* the rest of ssb-db2), indexing would not happen at all, the app seemed totally blank without content. On a second run of the app, indexing happens and content appears.
When using the migrate plugin alone, without ssb-db2, then the `sbot.close` hook does **not** run `log.close` (which should make sure all writes are done). This meant that `sbot.close` callbacks were called *before* AAOL was reading writing to disk.
ssb-db2/db.js already handles this case correctly, so we only need to patch the case where we are running `.use(require('ssb-db2/migrate'))` without `.use(require('ssb-db'))`, such that the close hook calls `log.close`.
=> fix migrate: close newLog when there  is no ssb-db2 installed

benchmark/index.js, encryption-formats/box2.js
This PR came out of a discussion about how box2 behaves when you are in a large number of groups. We decided to test this and to use this inform us about how we should go about decrypting group messages. The current strategy is to just try all keys in whatever order they were added. If you are in 1000 groups, then unboxing 1000 box2 messages takes around 30s. This is with 30% of the messages matching a group you are a part of (in other words, for 70% of the messages you try all 1000 keys in vain). The scaling is roughly linear, so 100 groups is ~3s.
Mix had an idea to use membership information to only try group keys that we know the author feed is a part of. This should provide a nice performance boost as you try a lot less keys, but complicates reindexing because you need a bit more …
=> Test performance of a large number of group keys

db.js, package.json, test/compaction.js
`compacting` is set to true only when `compactionProgress` reports something, but that could take a while (it needs to write a block in AAOL), and in the meantime, someone could call `ssb.db.query`, which can proceed if `compacting === false`.
As soon as we call `compact()`, set `compacting` to true.
=> dont allow queries to start when compact() just started

benchmark/index.js
Right now the box1 and box2 benchmarks don't decrypt anything because no messages are for you. While in the groups benchmark 30% is for you. This is confusion when reasoning about performance and also not super realistic. This PR changes things so that we can more easily compare things. See https://github.com/ssbc/ssb-db2/issues/346 for some numbers.
With this I think we can close #346. The conclusion is in https://github.com/ssbc/ssb-db2/issues/346#issuecomment-1184148122.
=> Improve box1 & box2 benchmarks

operators/index.js, test/operators.js
For issue #374. I noticed that I would just use `or(isEncrypted(), isDecrypted())` and that's a bit verbose so we can just have a shortcut.
See https://github.com/ssbc/ssb-subset-ql/blob/1f99976f59fc105b15bbab6fce4802d6d585580e/ql0.js#L89
=> bring back isPrivate() operator

README.md, core.js, test/basic.js
This is just because I want to avoid `getLog()` as a public API (I'm trying to reduce the amount of APIs in each library, this gives us more implementation flexibility), but we need a way of calling the `stats` method in AAOL.
=> add logStats() API

README.md, core.js
We have this API hacked in Manyverse already, would be nice to upstream it in ssb-db2: https://github.com/staltz/manyverse/blob/b0f5f4b17e85ac6d2777bd581dd084fbf97f5b59/src/backend/patches/ssb-db2%2B4.2.1.patch
=> add reset() API

core.js
We need this for pausing the ssb-friends / ssb-replication-scheduler integration, because indexingActive is triggered *right before* log.stream to update the indexes, and we need this "right before" behavior, that `status` doesn't give us.
I haven't thought out this API that well, I think in the future we could find a more developer friendly way of doing this.
=> add getIndexingActive() API

core.js, indexes/private.js, log.js, package.json, test/stream-decrypting.js
https://github.com/ssbc/ssb-replication-scheduler/issues/3
In privateIndex we use `streaming === true` to update the latestOffset, but this is troublesome if there is some live stream which takes the latest record in the log, because it'll update privateIndex's latestOffset and then when reindexing all previous records, we won't attempt to decrypt them because they aren't in the decrypted list and neither does the `recOffset > latestOffset` pass.
We should really only have one log.stream that is responsible for updating the private index. I elect the "leveldb log.stream" to be the only stream that can do that, thus we pass a `opts.shouldDecrypt = true` only for the core log.stream.
At the same time, this required fixing how log.stream was aborted. There was a race condition or something …
=> test streaming and decrypting records

core.js, test/create.js
https://github.com/ssbc/ssb-ebt/pull/71
We need to add an index message `[indexMsg, payload]` with the `sbot.db.addTransaction` API, such that the `indexMsg` is the "normal" part and the `payload` is the OOO part, but current addTransaction assumes that all of them have the same feed format.
This PR changes addTransaction internally, in a backwards-compatible way, so that the "nativeMsgs" part can be a different feed format to the "oooNativeMsgs" part.
=> allow heterogenous feed formats in addTransaction

core.js, test/minimal-db2.js
**Problem**: building a peer which doesn't do any encryption, but may want to publish things. Removing encryption reduces load on this peer (running on cheap droplet). The current code fails, even if you're not encrypting anything.
**Solution**: added a test case for minimal setup, and patched code to make it pass
=> No encryption

.gitignore, core.js, package.json, test/create.js
Leans on https://github.com/ssbc/ssb-classic/pull/2
This adds tests for over-sized classic messages (plaintext + encrypted).
TODO:
=> add tests for over-sized classic msgs, patch

core.js
I want to be able to just use box2, but when i took out box1 all my tests for encrypted messages were complaining.
ANNOYING AS SHIT
This inversion fixes it - i.e. only be fretting about encryptionFormat being present or not IF I'm possibly trying to encrrypt
=> fix annoying encryptionFormat bug

indexes/private.js
https://github.com/ssbc/ssb-ebt/issues/77
multicb is a bit tricky to use. It can generate CBs with `done()`, but if you call `done(() => {...` then it will **wait** for all the generated CBs to get called.
Problem here is that we were generating the CBs too late, we were generating them *after* the file had loaded, which meant that when it proceeded to `done((criticalError, results) => {` it was NOT waiting for files to be loaded, and thus we would always get offset `-1` for these indexes, which would cause a full rebuild of them.
Generate the multicb callbacks synchronously, before waiting for them.
Unfortunately no tests added because I'm confused as to how to test this. We don't have a proper hook to catch the moment when the private index is loaded. `onDrain` isn't that because it's …
=> correctly wait for private index loading

core.js, test/private-without-query.js
https://github.com/ssbc/ssb-ebt/issues/77
When the private index *alone* was being rebuilt, no other index, then Manyverse would not show a progress bar.
Private index is actually not included in the `status` object that is used for calculating indexing progress.
Now it is.
=> private index updates the status

core.js
This fixes #402. No need to load up all the offsets into memory if we just delete all of them anyway.
=> Simplify deleteFeed

README.md
Just a quick tip for other developers in the future, that toCallback can be an OOM footgun.
=> Recommend toPullStream over toCallback

compat/ebt.js, core.js
Out-of-memory crashes in Manyverse.
`pull.collect` considered harmful for RAM usage, because it internally accumulates an array of all stream items.
In a few cases, we don't strictly need `pull.collect`, and `pull.drain` / `pull.onEnd` are just fine.
=> avoid pull.collect to avoid OOM crashes

README.md, core.js, test/query-decrypted-box2.js, test/query-live-handle-box2-decrypts.js
This should fix #406
I went through a bit different solutions (see https://github.com/ssbc/jitdb/pull/236), but ended up with a new pull source api.
I considered doing this so the operators could be reused, but decided against that because the filtering is often pretty simple and this also shows people that doing a filter on the result is not that scary. Where this could also be useful is if you have something like do a rough filter on post but then filter the result only for specific stuff without creating an index in jitdb.
=> Add decrypted api for for box2 decrypted messages

core.js
Related to https://github.com/ssbc/async-append-only-log/pull/91. I tried the minimum possible to get things running again. A better fix would of course be to allow compaction to run in the browser, but for now I'd like to get things running again. See https://github.com/arj03/ssb-browser-core/issues/71.
=> Disable compaction in browser

core.js, test/ooo.js
https://github.com/ssbc/ssb-replication-scheduler/issues/14
`deleteFeed` doesn't support deleting messages that were added with OOO, because we have a `state` check, and addOOO has been recently updated #412 to not update the Base `state`.
Drop the `state` check in `deleteFeed`.
Add tests.
=> deleteFeed to support removing OOO

compat/history-stream.js, test/compat.js
updating scuttle-testbot and noticed that `createHistoryStream({ live: true })` was not supported
Added this along with tests
=> compat/history-stream - add support for { live }

README.md, indexes/plugin.js
In ssb-tribes2-demo we currently have to patch ssb-db2 to get it to run, see https://github.com/ssbc/ssb-tribes2-demo/issues/11 https://github.com/ssbc/ssb-tribes2-demo/blob/3d4425fec46894b4c0db601c312b65e9d58fe9ae/patches/ssb-db2%2B7.1.1.patch This config option should allow us to remove that patch.
I didn't add a test here but I'll make a PR in ssb-tribes2-demo where i test it
=> Add hasDiskAccess config

compat/db.js, compat/ebt.js, compat/feedstate.js, compat/log-stream.js, compat/publish.js
Made by @cooldracula in https://github.com/ssbc/ssb-db2/pull/424 first
=> Add hooks to compat functions
